### ISSUE TITLE
VoiceOver announces the button label twice

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-button#127] opened 2019-02-18 10:22 UTC
Using VoiceOver on the demo page, focusing the first button announces “Button Button, button”:
https://cdn.vaadin.com/vaadin-button/2.1.3/demo/#button-basic-demos (edited)

**Comment by web-padawan** [comment] 2019-02-18 10:47
Appears to be caused by #122 and #125. Should we revert these changes? 
Was the LightHosue warning incorrect (that was the reason to do that)?

**Comment by web-padawan** [comment] 2019-04-10 08:54
Closing as the code introducing this has been reverted and fix released in 2.1.5

**Closed by web-padawan** 2019-04-10 08:54 UTC
Labels: issue-backlog
